### PR TITLE
Build doc with sphinx.

### PR DESCRIPTION
**Pull request by Carreau**
Attempt to use sphinx to automatically build the documentation.

Using Shins has many advantages over using plain markdown files:

    - it is what most python project are doing, so you have better chances
    of finding help for it.
    - It can autogenerate API docs.
    - It can test that docs example are working which prevent any
    regressions.
    - You can use services like Readthedocs.org to automatically build your
    documentation for your user, and it will crosslink with projects that
    are also using sphinx and are either dependant (or dependees) of your
    project.

That may require some changes to docstrings as there are some standard
in the Python community as to to how to format docstrings, but
consistency across projects is generally good.

--- 

That is built on top of the Other Python 3 Compat PR, but have some intermediate commits that should be removed before merge. 

I would of course understand if you wish not to use sphinx.

### CODE REVIEW

**Comment by Carreau** [comment]
@blubbundbla I've updated this branch to be the minimal changes to allow sphinx to build on python 2.7. 

you can build from the root with `make html -C docs/` and you'll find the built docs in `docs/build/html/index.html`

**Comment by Carreau** [comment]
you may need to install m2r and recommonmark for things to wirk.

**Comment by Carreau** [comment]
Both `master` and `dev` docs can be found [there](https://physcraper.readthedocs.io/)

**Comment by Carreau** [comment]
@blubbundbla I would also recommend https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard if you need advinces on how to format docstrings.

**Comment by Carreau** [comment]
Hum, I don't see any error. What did you type and what error do you get ? I'll try in a fresh env.

**Comment by Carreau** [comment]
So I just did the following in a new env:

```
pip install -r requirements.tst
pip install . 
pip install sphinx 
make C docs html
```

And that appear to work. I'll try to run the tests.

**Comment by blubbundbla** [comment]
Sorry, it seems I was not clear enough. I came across it when I wanted to get a new venv on the cluster. So then I went to my on machine to investigate. When I initiate a new virtual environment with a new git clone on my computer, the python setup.py and requirements give me new warnings and errors. But it actually seems that i can still run the tests. When I do it on the cluster though, the error messages are even more and of different kind. I can still start runs, but they exit after some time, with an error in a peyotl function. This is why I assumed it might be related to the warnings with the Makefile (line 4 in the error message).

my history:
 2002  mkdir test
 2003  cd test
 2004  virtualenv -p /usr/bin/python venv-test
 2005  source venv-test/bin/activate
 2006  git clone https://github.com/McTavishLab/physcraper.git
 2007  cd physcraper/
 2009  python setup.py develop
 
my error message (partial):
setuptools command extensions are available
coverage analysis not available
file peyotl.py (for module peyotl) not found
warning: no files found matching 'doc/Makefile'
warning: no files found matching '*' under directory 'doc/source'
warning: no previously-included files matching '.DS_Store' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '.gitignore' found anywhere in distribution
file peyotl.py (for module peyotl) not found
file peyotl.py (for module peyotl) not found
Moving peyotl-0.1.2-py2.7.egg to /home/blubb/test/venv-test/lib/python2.7/site-packages
Adding peyotl 0.1.2 to easy-install.pth file
.....
Searching for dendropy==4.1.0
Reading https://pypi.org/simple/dendropy/
Downloading https://files.pythonhosted.org/packages/65/3a/19556a58c560de488dffbf3c7fe7c9ed34c1a6223f0dfe971224a42aaf39/DendroPy-4.1.0.tar.gz#sha256=c3d4b2780b84fb6ad64a8350855b2d762cabe45ecffbc04318f07214ee3bdfc9
Best match: DendroPy 4.1.0
Processing DendroPy-4.1.0.tar.gz
Writing /tmp/easy_install-PDQtCN/DendroPy-4.1.0/setup.cfg
Running DendroPy-4.1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-PDQtCN/DendroPy-4.1.0/egg-dist-tmp-2hssWV
DendroPy version   : DendroPy 4.1.0
DendroPy location  : /tmp/easy_install-PDQtCN/DendroPy-4.1.0/dendropy
Python version     : 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
Python executable  : /home/blubb/test/venv-test/bin/python
-setup.py: None
-setup.py: using distutils
-setup.py: using canned package list
-setup.py: packages identified:
                                dendropy : dendropy
                      dendropy.calculate : dendropy/calculate
                         dendropy.dataio : dendropy/dataio
                      dendropy.datamodel : dendropy/datamodel
                        dendropy.interop : dendropy/interop
                         dendropy.legacy : dendropy/legacy
                        dendropy.mathlib : dendropy/mathlib
                          dendropy.model : dendropy/model
                       dendropy.simulate : dendropy/simulate
                           dendropy.test : dendropy/test
                        dendropy.utility : dendropy/utility
                dendropy.utility.libexec : dendropy/utility/libexec

-setup.py: scripts identified: applications/sumtrees/sumtrees.py
-setup.py: setuptools command extensions are available
coverage could not be imported: test coverage analysis not available
-setup.py: coverage analysis not available
warning: no previously-included files matching '.DS_Store' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '.gitignore' found anywhere in distribution
warning: no previously-included files matching '.gitattributes' found anywhere in distribution
warning: no previously-included files matching '.idea' found anywhere in distribution
warning: no previously-included files matching '__pycache__' found anywhere in distribution
Moving DendroPy-4.1.0-py2.7.egg to /home/blubb/test/venv-test/lib/python2.7/site-packages
Adding DendroPy 4.1.0 to easy-install.pth file
Installing sumtrees.py script to /home/blubb/test/venv-test/bin


and then after doing: pip install -r requirements.txt

Traceback (most recent call last):
  File "/home/blubb/test/venv-test/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/blubb/test/venv-test/local/lib/python2.7/site-packages/pip/_internal/__init__.py", line 78, in main
    return command.main(cmd_args)
  File "/home/blubb/test/venv-test/local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 184, in main
    timeout=min(5, options.timeout)
  File "/home/blubb/test/venv-test/local/lib/python2.7/site-packages/pip/_internal/cli/base_command.py", line 79, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/home/blubb/test/venv-test/local/lib/python2.7/site-packages/pip/_internal/download.py", line 337, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/home/blubb/test/venv-test/local/lib/python2.7/site-packages/pip/_internal/download.py", line 126, in user_agent
    setuptools_version = get_installed_version("setuptools")
  File "/home/blubb/test/venv-test/local/lib/python2.7/site-packages/pip/_internal/utils/misc.py", line 836, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/home/blubb/test/venv-test/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 562, in __init__
    self.add_entry(entry)
  File "/home/blubb/test/venv-test/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 618, in add_entry
    for dist in find_distributions(entry, True):
  File "/home/blubb/test/venv-test/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1883, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/home/blubb/test/venv-test/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1402, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/home/blubb/test/venv-test/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1757, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/home/blubb/test/venv-test/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1634, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/home/blubb/test/venv-test/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1591, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/home/blubb/test/venv-test/local/lib/python2.7/site-packages/peyotl-0.1.2-py2.7.egg'

**Comment by Carreau** [comment]
That seem unrelated to physcraper itslelf. I'll try to reproduce on the cluster.

**Comment by snacktavish** [comment]
Can you post a script that gives you these errors?

**Comment by blubbundbla** [comment]
1. On my computer

a) with error messages:

virtualenv -p /usr/bin/python venv-test
source venv-test/bin/activate
git clone https://github.com/McTavishLab/physcraper.git
cd physcraper
python setupt.py develop 
deactivate


b) no error messages:

rm -r docs/source/
rm docs/Makefile
rm make.bat

virtualenv -p /usr/bin/python venv-test2
source venv-test2/bin/activate
python setupt.py develop 


2. on the cluster:

virtualenv -p /usr/bin/python venv-test
source venv-test/bin/activate
git clone https://github.com/McTavishLab/physcraper.git
cd physcraper
pip install --upgrade setuptools
python setupt.py develop

**Comment by blubbundbla** [comment]
uploaded them as bash scripts to the test folder:
venv_error_v1.sh -> produces error
venv_error_v2.sh -> produces none
venv_error_cluster.sh -> for the cluster, produces errors

**Comment by Carreau** [comment]
Ok, so I've seen the error, but it seem to go away if I : 

```
pip install setuptools --upgrade 
```

Before trying to `pip install -r requirements.txt`. 

I'm going to redo that from another clean env to make sure.

**Comment by Carreau** [comment]
Ok that is weird. running the same thing I sometime get the error, sometime not

**Comment by Carreau** [comment]
... ok so I sometime see the error message, but it's not clear why. 
Usually if I rerun the `pip install -r requirements.txt` it works w/o a hiccups. 

I've tried to remove /docs/source/ as well, and I still sometime see the error. So it's unsure what is happening.

**Comment by Carreau** [comment]
Ok, I think I might have an idea. It depends wether you setup.py devevelop first ; or pip install requirements.txt first. So it might be peyotl doing a weird thing.

**Comment by Carreau** [comment]
So these two things works reliably for me.

Two things: 

1) `pip install -e .`  instead of `python setup.py develop`, it's almost the same if you are developping, on the cluster `pip install .` shoudl be sufficient as well.

2) get rid of `m2r`, because on MECED python is too old. 

3) if we install physcraper first, we need to avoid using `setuptools`, or it will pull a more rencent peyotl which screw up things. 

`[mbussonnier@merced] ~ $ cat phytest-reqlast`
```
mkdir $1
echo $(tput setaf 2)Creating Venv in $1$(tput sgr0)
cd $1
virtualenv -p /usr/bin/python venv-$1 1>/dev/null
source venv-$1/bin/activate

echo $(tput setaf 2)Upgrading Pip and setuptools.... $(tput sgr0)
pip install -q pip --upgrade 1>/dev/null 2>&1
pip install -q setuptools --upgrade 1>/dev/null

echo $(tput setaf 2)Clonning...$(tput sgr0)
git clone https://github.com/McTavishLab/physcraper.git --depth=1 1>/dev/null 2>&1

cd physcraper/

sed -i'' '/m2r/d' requirements.txt
sed -i'' 's/from setuptools import setup/from distutils.core import setup/g' setup.py

echo $(tput setaf 2)Installign Physcrapper$(tput sgr0)
pip install -e .

echo $(tput setaf 2)Installing Requirements$(tput sgr0)
pip install -q -r requirements.txt

echo 'no' | python tests/testfilesetup.py
```


`$ cat phytest-reqfirst`
```
mkdir $1
echo $(tput setaf 2)Creating Venv in $1$(tput sgr0)
cd $1
virtualenv -p /usr/bin/python venv-$1 1>/dev/null
source venv-$1/bin/activate

echo $(tput setaf 2)Upgrading Pip and setuptools.... $(tput sgr0)
pip install -q pip --upgrade 1>/dev/null 2>&1
pip install -q setuptools --upgrade 1>/dev/null

echo $(tput setaf 2)Clonning...$(tput sgr0)
git clone https://github.com/McTavishLab/physcraper.git --depth=1 1>/dev/null 2>&1

cd physcraper

sed -i'' '/m2r/d' requirements.txt


echo $(tput setaf 2)Installing Requirements$(tput sgr0)
pip install -q -r requirements.txt

echo $(tput setaf 2)Installign Physcrapper$(tput sgr0)
pip install -e .

echo "no" | python tests/testfilesetup.py
```

**Pull request merged**
